### PR TITLE
fix(src): websocket provider set header

### PR DESCRIPTION
**Pull request by ChasLui**
use provider in nodejs, should set cookie to auth

### CODE REVIEW

**Comment by dmonad** [comment]
I like this. But the last time I checked not all browsers supported headers in Websocket connections. Some just ignore the headers option. Can you please check whether this works in Chrome, Firefox, and Safari?

**Comment by ChasLui** [comment]
> I like this. But the last time I checked not all browsers supported headers in Websocket connections. Some just ignore the headers option. Can you please check whether this works in Chrome, Firefox, and Safari?

Unfortunately, the websocket headers cannot be set in Chrome, Firefox, and Safari browsers

**Comment by dmonad** [comment]
I'm a bit confused. So what does this PR achieve?

**Comment by hanspagel** [comment]
I think he wants support in Node.js (see initial comment).

**Comment by ChasLui** [comment]
> I'm a bit confused. So what does this PR achieve?



> I'm a bit confused. So what does this PR achieve?

**Comment by ChasLui** [comment]
> I'm a bit confused. So what does this PR achieve?

When using require('ws') as WebSocketPolyfill in nodejs, it is necessary to set the cookie. For more details, see https://github.com/websockets/ws/issues/1411

**Comment by dmonad** [comment]
Setting a cookie is optional. But since this would only enable cookies in `Websocket` provided by `ws`, and because it is incompatible with the `Websocket` constructor provided by the browser, I'm a bit hesitant to merge this.

**Pull request closed without merging**
